spring:
  main:
    banner-mode: 'off'

logging:
  level:
    #org:
      #springframework: 'WARN'
      #springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: 'INFO'
      #apache:
        #catalina: 'WARN'
        #directory: 'WARN'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} [%15.15t] %35.35logger{34} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

---
spring:
  profiles: systemd

logging:
  pattern:
    console: '%d{.SSS} ${LOG_LEVEL_PATTERN:%5p} [%15.15t] %35.35logger{34} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
